//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Maps.MapControl.WPF;

    public partial class Objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objects()
        {
            this.Lines = new HashSet<Lines>();
            this.Lines1 = new HashSet<Lines>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Location Loc
        {
            get { return new Location(Latitude, Longitude); }
            set { Loc = value; }
        }
        public int Voltage { get; set; }
        public int Type { get; set; }
        public string ToolTip
        {
            get
            {
                return Id + Name + "\nLatitude: " + Convert.ToString(Latitude).Replace(',', '.') + "\nLongitude: "
                  + Convert.ToString(Longitude).Replace(',', '.')
                  + "\nType: " + Types.Type + "\nVoltage: " + Voltage_levels.Voltage;
            }
            set { ToolTip = value; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lines> Lines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lines> Lines1 { get; set; }
        public virtual Types Types { get; set; }
        public virtual Voltage_levels Voltage_levels { get; set; }
    }
}
