//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int Voltage { get; set; }
        public int Type { get; set; }
    
        public virtual Types Types { get; set; }
        public virtual Voltage_levels Voltage_levels { get; set; }
    }
}
